### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by arsham6ix** [hawshemi/Linux-Optimizer#17]
درود

بنظرم اگه برای هر مرحله If قرار بدید خیلی بهتر میشه چون ی سری هاشو شاید یکی نخواد بزنه رو سرورش

مثلا قسمت اخر که میشه پورت ها رو من یکی به شخصه استفاده نمیکنم حالا باید وقت بزارم همه پورت هایی که باز کرده رو دونه دونه ببندم.

ممنون بابت اسکریپ

**Comment by hawshemi** [comment]
The Menu is Added Now.
Thanks for your feedback.
