### ISSUE TITLE
Loop with ubuntu user[BUG]

### ISSUE THREAD

**Issue by amirmohamadamini** [hawshemi/Linux-Optimizer#22]
When i run it with this command on my server which is not  root user by default, it falls in to a Loop.
`sudo bash< <(curl -s https://raw.githubusercontent.com/hawshemi/Linux-Optimizer/main/linux-optimizer.sh)
`

It give me this error and contiue showing the menu.
`[*] ----- Wrong input!`

 - OS: Ubuntu
 - Version: 22

**Comment by amirmohamadamini** [comment]
If i switch to root user with ` sudo -i` it works ok.

**Comment by hawshemi** [comment]
The script is updated.
You should run `sudo -i` first and then the `bash` command.

Thanks for your feedback.
