### ISSUE TITLE
تعدادى ايده

### ISSUE THREAD

**Issue by VahidN** [hawshemi/Linux-Optimizer#24]
دو سري تنظيمات ويژه‌ي جهت بهبود كارآيي شبكه را در اينجا ديدم كه مي‌توانند براي تكميل پروژه مفيد باشند:
https://gist.github.com/hiqsociety/2a4c26123df181bcdd3f1a0d42c7ee03
https://gist.github.com/jedi4ever/903751

**Comment by hawshemi** [comment]
ممنون. در حال تحقیق هستم که به بهترین حالت sysctl.conf برسم.
اگر ایده های دیگری هم دیدید همینجا در میون بگذارید.

**Comment by VahidN** [comment]
[اين فورك هم](https://github.com/samsesh/Ubuntu-Optimizer) بر اساس همين پروژه است و تكميل شده و مختص Ubuntu.

**Comment by hawshemi** [comment]
>https://gist.github.com/hiqsociety/2a4c26123df181bcdd3f1a0d42c7ee03 

Updated version: http://klaver.it/linux/

**Comment by hawshemi** [comment]
The script is updated with new settings for `sysctl.conf`.

https://github.com/hawshemi/Linux-Optimizer/tree/main/files
