### ISSUE TITLE
[BUG] netplan not found ubuntu 18.04

### ISSUE THREAD

**Issue by avr68** [hawshemi/Linux-Optimizer#29]
سلام رو ابونتو 18 ران شد 
نتورک دیگه بعد ریست بالا نیومد و سیستم عامل دیگه netplan رو نمیشناخت

**Comment by hawshemi** [comment]
ورژن اوبونتو دقیق شما 18.04 هست؟
منظور از بالا نیومدن نتورک چی هست؟ ارور و یا اخطار خاصی میده؟

**Comment by avr68** [comment]
بله
![Screenshot from 2023-06-17 11-22-11](https://github.com/hawshemi/Linux-Optimizer/assets/19828162/1b8b943f-a014-4be0-8111-a17d414232fd)
چند دفه ای هم از اول سیستم عامل نصب کردیم همین شد!!
با ۱۸ به بالا اوکی کار میکنه ولی با خود ۱۸.۰۴ نه

**Comment by hawshemi** [comment]
عجیبه چون روی 18.04 LTS هم تست شده بوده و کاری به net-plan نداره.

همین الان هم یه سرور 18.04 گرفتم و تست کردم. بعد از ریبوت مشکلی نداشت و به درستی کار میکرد.

دسترسی از VNC دارید؟

**Comment by avr68** [comment]
اره 
بذار من اگه ماشین خالی داشتم مجدد تست میکنم ایمج ها ما پارس پک هست احتمال این دستکاری شده باشه هم هست 
در هر صورت گفتم در جریان باشی چون برا من خیلی دردسر ساز شد 
اگه بازم پیش امد بهت میگم سعی میکنم یه لاگ یا ویدیو بگیرم برات

**Comment by hawshemi** [comment]
اره بعضی ارائه دهنده ها روی ایمیج ها دسکاری میکنن و تنظیمات رو بهم میزنن (پارس پک هم معروفه به داستان سازی -_- )
ولی الان اینترفیس شما `DOWN` شده. اینکار رو تست کن ببین درست میشه یا نه:

```
sudo nano /etc/netplan/50-cloud-init.yaml
```
داخل این فایل `ens18` رو پیدا کن:
```
ens18:
  dhcp4: true
  optional: true
```
مطمئن شو که `dhcp4` برابر با `true` باشه.

بعد ریلود کن:
```
sudo netplan apply
```
```
sudo systemctl restart systemd-networkd
```

**Comment by avr68** [comment]
کلا دستور netplanرو سیستم نمیشناسه :)

**Comment by hawshemi** [comment]
مطمئنی قبلا میشناخت؟
روی بعضی سرور ها یجوری دیگه مانفیگ میکنن بجای `netplan`

این سه تارو بزن ببین کدوم ارور نمیده:

```
sudo systemctl restart NetworkManager
```
```
sudo systemctl restart systemd-networkd
```
```
sudo systemctl restart networking
```

**Comment by avr68** [comment]
اره میشناخت 
هرچی که فک کنی زدیم فایده نداشت

**Comment by hawshemi** [comment]
اصولا قبل از اپدیت ها من روی همه ایمیج های معروف با ورژن های مختلف تست میکنم. اگر مشکلی نداشت اسکریپت تازه اپدیت میشه.
این قضیه که شما میگی دستکاری های پارسپک میتونه باشه. شاید درست نیست گفتنش ولی خب پیشنهاد میکنم ارائه دهنده رو عوض کنید و از اوبونتو ورژن بالاتری `(LTS)` استفاده کنید.

**Comment by avr68** [comment]
اره منم تو همین فکرم پشتبانی شون هم دیگه هیچی رو گردن نمیگیره دیر سین میزنه :))))
