### ISSUE TITLE
Xanmod install

### ISSUE THREAD

**Issue by iamfarhad** [hawshemi/Linux-Optimizer#42]
نصب xanmod کلا سرور هامو کند کرده و غیرقابل استفاده

**Comment by hawshemi** [comment]
بیشتر توضیح بدید لطفا.
منظور از کندی چیه؟
منظور از غیر قابل استفاده چیه؟

**Comment by iamfarhad** [comment]
به شدت پینگ سرویس هام و کانفیگ هام رفت و بالا و ناپایدار شد. در صورتی که قبل نصب xanmod اوکی بود همه چیز

**Comment by hawshemi** [comment]
از ترمینال خود سرور پینگ 1.1.1.1 و پینگ 8.8.8.8 بگیرید ببینید اوکی هست یا نه. اصولا  نباید بالاتر از نرمال باشه.

**Comment by hawshemi** [comment]
همینطور بفرمایید که سرور ایران نصب کردید؟
پیش اومده که سرور کلا پینگ نده؟ یا فقط کند میشه؟

**Comment by NoRRt** [comment]
سلام و خسته نباشید - اره واسه من کند شده - روی سرور هلند این اسکریپت شما رو نصب کردم و زمانی که (Xray & Sing-Box) هر پنلی نصب میکنید وبا کلاینت ها کانکت میشی کندی روی ارسال و دریافت احساس می کنید .  زمانی که بروز رسانی ها رو انجام دادیم به این مشکل برخوردیم احتمالا از (Xanmod) باشه . با تشکر

**Comment by iamfarhad** [comment]
هم سرور ایران نصب کردم هم خارج
کند شد اما پینگ قطع نشد

درآخر با ریبیلد حل شد مشکلم

**Comment by hawshemi** [comment]
آیا گزینه ی  1 که Apply Everything هست رو زدید؟

**Comment by NoRRt** [comment]
> آیا گزینه ی 1 که Apply Everything هست رو زدید؟

بله . بعدش دوباره سرور رو دوباره ریست کلی کردم . بعد گزینه 2 رو زدم 
تست کردم بهتر شد.

**Comment by hawshemi** [comment]
لازم نیست گزینه ی 2 رو بزنید اگر گزینه ی 1 رو زدید.

**Comment by hawshemi** [comment]
اسکریپت هم آپیدت شد و یکسری باگهای جزئی برطرف شده.
لطفا دوباره ران کنید و گزینه 1 رو بزنید و ریبوت کنید.

**Comment by iamfarhad** [comment]
بچز lts شدن xanmod  و تغییر منو کت تغییر خاصی نداشته؟

**Comment by hawshemi** [comment]
قسمت آپدیت و تمیز کاری بعد نصب xanmod هم یخورده بهتر شده.

**Comment by NoRRt** [comment]
سلام و خسته نباشید - ما ی سورسی بروز پیدا کردیم فکر امکانات خوبی برای بهینه سازی داشته باشه -  اگر امکانش هست به سروس خودتون اضافه کنین جواب بده 
https://kejilion.blogspot.com/2023/10/bbrv3-vps.html

**Comment by hawshemi** [comment]
تشکر. حتما چک میکنم.

**Comment by NoRRt** [comment]
تو این اسکریپت تنظیمات DNS به این شکله - حالا ممکنه تاثیر داشته باشه.؟

Do you want to set the DNS address to Cloudflare and Google? (y/n): 
Set DNS for Cloudflare and Google
DNS address updated
--------------------------
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 2606:4700:4700::1111
nameserver 2001:4860:4860::8888

**Comment by hawshemi** [comment]
الان چک کردم اسکریپت رو.
کار مفیدی انجام نمیده. بهترین کارش همین نصب xanmod و bbrv3 هست. بقیه چیزهاش به درد ما نمیخوره اصلا و الکی سرور رو bloated و سنگین میکنه.

این DNS هایی که گذاشته، DNS ورژن 6 گوگل هم هست. طبیعتا سروری که روش داره نصب میشه باید اول IPv6 داشته باشه بعد DNSv6 روش نصب بشه. برای همین اول باید چک بشه که سرور اصلا IPv6 داره یا خیر.
و برای ما ایرانی ها، DNS های کلودفلر روی پروکسی ها خیلی بهتر از گوگل جواب میده.

**Comment by iamfarhad** [comment]
الان توی اسکریپت شما bbr3 نصب میشه یا نه؟

**Comment by hawshemi** [comment]
بله. با نصب xanmod بصورت دیفالت bbrv3 هم فعال میشه.

**Comment by hawshemi** [comment]
این اسکریپت بیشتر تمرکزش روی نصب ابزار ها و اپلیکیشن های مختلف روی سیستم هست تا بهینه سازی سیستم.
اسکریپت من، تمرکزش روی بهینه سازی خود سیستم عامل و هسته ی لینوکس هست که بشه با یک دکمه روی تمام سرورها اجرا کرد.

شما از اون اسکریپت کدوم کارهاشو دیدید و استفاده میکنید؟

**Comment by NoRRt** [comment]
XanMod Linux  BBR3 من اینو نصب کردم جواب نسبتا بهتری گرفتم

**Comment by NoRRt** [comment]
یه اسکریپت هست  مثل  اسکریپت شما ایرانی هست -[Vps](https://github.com/opiran-club/VPS-Optimizer)  این هم بروز رسانی میکنه =

**Comment by hawshemi** [comment]
کلا الان برای فعالسازی BBRv3 راحت ترین و پایدارترین راه، نصب XanMod هست.

**Comment by hawshemi** [comment]
> یه اسکریپت هست مثل اسکریپت شما ایرانی هست -[Vps](https://github.com/opiran-club/VPS-Optimizer) این هم بروز رسانی میکنه =

بله این اسکریپت فورکی از همین اسکریپت من هست.
