### ISSUE TITLE
[BUG]آیا راهی برای پاک کردن و برگشت به حالت قبل هست

### ISSUE THREAD

**Issue by hatinati2** [hawshemi/Linux-Optimizer#44]
سلام وقت بخیر
آیا راهی برای پاک کردن و برگشت به حالت قبل هست
از وقتی روی سروری که پنل هدیفای نصب بوده ، اسکریپت نصب کردم cpu  از 75درصد پایین تر نمیاد و در روز چندبازی سرور دان میشه مجبور می شوم سرور از پنل ریبوت کنم 
سرور 4هسته 3gh و 8گیگ ram  دارد
متشکر می شوم راهنمایی بفرمایید

**Comment by hawshemi** [comment]
یک تغییری دادم هسته ی xanmod رو.
یکبار دیگه اسکریپت رو ران کنید و xanmod رو نصب کنید.

**Comment by hatinati2** [comment]
مرسی متشکرم الان تست می کنم

**Comment by hatinati2** [comment]
دست شما درد نکنه 
یک دنیا تشکر 
درست شد
مرسی

**Comment by hawshemi** [comment]
ممنون از شما بابت گزارش.

**Comment by hatinati2** [comment]
قربان شما سلامت باشید
