### ISSUE TITLE
After each login to Ubuntu Machine, I encounter the following errors:

### ISSUE THREAD

**Issue by arvinab** [hawshemi/Linux-Optimizer#47]
-bash: ulimit: pending signals: cannot modify limit: Operation not permitted
-bash: ulimit: max locked memory: cannot modify limit: Operation not permitted
-bash: ulimit: POSIX message queues: cannot modify limit: Operation not permitted
unlimited
-bash: ulimit: max user processes: cannot modify limit: Operation not permitted

**Comment by hawshemi** [comment]
Can you check `ssh` settings?

```
sudo nano /etc/ssh/sshd_config
```

Is there a line like this?:
```
UsePAM=yes
```

If not, add it and then reboot the server.

**Comment by hawshemi** [comment]
And please state your Ubuntu version.

**Comment by cdnov** [comment]
I also encountered this problem. System version Ubuntu 22.04

**Comment by cdnov** [comment]
> Can you check `ssh` settings?
> 
> ```
> sudo nano /etc/ssh/sshd_config
> ```
> 
> Is there a line like this?:
> 
> ```
> UsePAM=yes
> ```
> 
> If not, add it and then reboot the server.

Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 6.1.59-x64v2-xanmod1 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Oct 25 10:03:58 PM MST 2023

  System load:  0.0498046875       Temperature:           30.0 C
  Usage of /:   14.8% of 97.87GB   Processes:             550
  Memory usage: 0%                 Users logged in:       0
  Swap usage:   0%                 IPv4 address for eno2: 0.0.0.0

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


Last login: Wed Oct 25 22:04:00 2023 from 0.0.0.0
-bash: ulimit: pending signals: cannot modify limit: Operation not permitted
-bash: ulimit: max locked memory: cannot modify limit: Operation not permitted
-bash: ulimit: POSIX message queues: cannot modify limit: Operation not permitted
unlimited
-bash: ulimit: max user processes: cannot modify limit: Operation not permitted

**Comment by hawshemi** [comment]
@cdnov 
Did you check the `UsePAM=yes` setting?

**Comment by cdnov** [comment]
root@ubuntu:/home/ubuntu# cat /etc/ssh/sshd_config

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

Include /etc/ssh/sshd_config.d/*.conf

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers aes256-ctr,chacha20-poly1305@openssh.com
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.#AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
KbdInteractiveAuthentication no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the KbdInteractiveAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via KbdInteractiveAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and KbdInteractiveAuthentication to 'no'.
UsePAM yes

#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#PermitUserEnvironment no
#Compression delayed
#UseDNS no
#PidFile /run/sshd.pid
#MaxStartups 10:30:100
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem       sftp    /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       PermitTTY no
#       ForceCommand cvs server
TCPKeepAlive yes
ClientAliveInterval 3000
ClientAliveCountMax 100
AllowAgentForwarding yes
AllowTcpForwarding yes
GatewayPorts yes
PermitTunnel yes
X11Forwarding yes
UsePAM=yes
root@ubuntu:/home/ubuntu#

**Comment by hawshemi** [comment]
I noticed `root@ubuntu:/home/ubuntu#`. do you have another user? Does your VPS provider have some sort of limitations for users?

**Comment by cdnov** [comment]
dedicated server
```
ubuntu@ubuntu:~$ su
Password: 
root@ubuntu:/home/ubuntu# cd
root@ubuntu:~# cat /etc/profile/
cat: /etc/profile/: Not a directory
root@ubuntu:~# 
```

**Comment by hawshemi** [comment]
Okay, there are no profile file for some reason!
Run this command to make it:

```
wget "https://raw.githubusercontent.com/hawshemi/Linux-Optimizer/main/files/profile" -q -O /etc/profile
```

**Comment by hawshemi** [comment]
delete the `/` at the end of directory:

```
cat /etc/profile
```

**Comment by cdnov** [comment]
```
root@ubuntu:~# cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "$(id -u)" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
ulimit -c unlimited
ulimit -d unlimited
ulimit -f unlimited
ulimit -i unlimited
ulimit -l unlimited
ulimit -m unlimited
ulimit -n 1048576
ulimit -q unlimited
ulimit -s -H 65536
ulimit -s 32768
ulimit -t unlimited
ulimit -u unlimited
ulimit -v unlimited
ulimit -x unlimited
```

**Comment by hawshemi** [comment]
OK, and can you run these commands manually to check their output:

```
ulimit -i unlimited
```
```
ulimit -l unlimited
```
```
ulimit -q unlimited
```
```
ulimit -u unlimited
```

**Comment by cdnov** [comment]
```
root@ubuntu:~# ulimit -i unlimited
root@ubuntu:~# ulimit -l unlimited
root@ubuntu:~# ulimit -q unlimited
root@ubuntu:~# ulimit -u unlimited

```

**Comment by hawshemi** [comment]
now can you reboot the system to check if those errors are gone or not?

**Comment by cdnov** [comment]
Restarted and it still doesn’t disappear.

**Comment by hawshemi** [comment]
now show me this:
```
ulimit -a
```

**Comment by cdnov** [comment]
```
root@ubuntu:~# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) unlimited
max locked memory           (kbytes, -l) unlimited
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) unlimited
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) unlimited
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

**Comment by hawshemi** [comment]
It's rather strange, every ulimit os ok except `ulimit -n`.
can you enter this:
```
ulimit -n 1048576
```

**Comment by hawshemi** [comment]
Also,
check these files:
```
cat /etc/security/limits.conf
```
```
cat /etc/security/limits.d/
```

**Comment by cdnov** [comment]
> It's rather strange, every ulimit looks ok except `ulimit -n`. can you enter this:
> 
> ```
> ulimit -n 1048576
> ```
```

root@ubuntu:/home/ubuntu# ulimit -n 1048576
root@ubuntu:/home/ubuntu# 
```

**Comment by cdnov** [comment]
> Also, check this file:
> 
> ```
> cat /etc/security/limits.conf
> ```
> 
> And if any files exist at `/etc/security/limits.d/` ?

```
root@ubuntu:/home/ubuntu# cat /etc/security/limits.conf
# /etc/security/limits.conf
#
#Each line describes a limit for a user in the form:
#
#<domain>        <type>  <item>  <value>
#
#Where:
#<domain> can be:
#        - a user name
#        - a group name, with @group syntax
#        - the wildcard *, for default entry
#        - the wildcard %, can be also used with %group syntax,
#                 for maxlogin limit
#        - NOTE: group and wildcard limits are not applied to root.
#          To apply a limit to the root user, <domain> must be
#          the literal username root.
#
#<type> can have the two values:
#        - "soft" for enforcing the soft limits
#        - "hard" for enforcing hard limits
#
#<item> can be one of the following:
#        - core - limits the core file size (KB)
#        - data - max data size (KB)
#        - fsize - maximum filesize (KB)
#        - memlock - max locked-in-memory address space (KB)
#        - nofile - max number of open file descriptors
#        - rss - max resident set size (KB)
#        - stack - max stack size (KB)
#        - cpu - max CPU time (MIN)
#        - nproc - max number of processes
#        - as - address space limit (KB)
#        - maxlogins - max number of logins for this user
#        - maxsyslogins - max number of logins on the system
#        - priority - the priority to run user process with
#        - locks - max number of file locks the user can hold
#        - sigpending - max number of pending signals
#        - msgqueue - max memory used by POSIX message queues (bytes)
#        - nice - max nice priority allowed to raise to values: [-20, 19]
#        - rtprio - max realtime priority
#        - chroot - change root to directory (Debian-specific)
#
#<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#root            hard    core            100000
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#ftp             -       chroot          /ftp
#@student        -       maxlogins       4

# End of file
root@ubuntu:/home/ubuntu# 
```

**Comment by hawshemi** [comment]
Everything seems fine.
Until I find out what happened, you can fix the errors by doing this:

```
nano /etc/profile
```
Then delete these lines:
```
ulimit -i unlimited
ulimit -l unlimited
ulimit -q unlimited
ulimit -u unlimited
```
reboot.

**Comment by cdnov** [comment]
> Everything seems fine. Until I find out what happened, you can fix the errors by doing this:
> 
> ```
> nano /etc/profile
> ```
> 
> Then delete these lines:
> 
> ```
> ulimit -i unlimited
> ulimit -l unlimited
> ulimit -q unlimited
> ulimit -u unlimited
> ```
> 
> Save the file: `Ctrl+X` then `Y` then `Enter`.
> 
> Reboot.

Thanks. Hope the menu can be optimized

**Comment by cdnov** [comment]
> > -bash: ulimit: pending signals: cannot modify limit: Operation not permitted -bash: ulimit: max locked memory: cannot modify limit: Operation not permitted -bash: ulimit: POSIX message queues: cannot modify limit: Operation not permitted unlimited -bash: ulimit: max user processes: cannot modify limit: Operation not permitted
> 
> Do you use an AWS VPS?

NO

**Comment by hawshemi** [comment]
I tested with many servers and discovered that if you `SSH` to the server with a username other than `root`, those errors show up.
You have to `SSH` to the server with the `root` username directly.
