### ISSUE TITLE
BBR VS hybla[SUGGESTION]

### ISSUE THREAD

**Issue by NoRRt** [hawshemi/Linux-Optimizer#48]
سلام و خسته نباشید - بین hybla و BBr  فرقی هست و اگر هست توی سرور  از hybla استفاده بشه نسبت به BBR تاثیری بر روی سرور احساس میشه . مثلا = پینگ .. یا پکت لاس ...

**Comment by hawshemi** [comment]
بله Hybla از BBRv1 بهتره.
اما [BBRv3 ](https://github.com/google/bbr/tree/v3)جدید اومده که باگفیکس BBRv2 هست. و طبق بنچ مارک های گوگل، فعلا از تمام Congestion Control ها بهتر و پایدارتر عمل میکنه.
پس فعلا بهترین گزینه BBRv3 هست که با نصب XanMod بطور دیفالت فعال میشه.
