### ISSUE TITLE
Adding Selective WARP [SUGGESTION]

### ISSUE THREAD

**Issue by Phoenix-999** [hawshemi/Linux-Optimizer#49]
Thanks for Linux-Optimizer 
Would be wonderful if you could add selective WARP to your wonderful script in the next update

Thank you in advance and keep up the good work✌🏽

**Comment by hawshemi** [comment]
This script is for optimizing Linux. I think WARP is out of scope.
Also, for Using warp, xray-core supports `wireguard` protocol in itself. you don't need any warp script for that.
https://github.com/chika0801/Xray-examples/blob/main/wireguard.md
