### ISSUE TITLE
TCP packet sending algorithm

### ISSUE THREAD

**Issue by NoRRt** [hawshemi/Linux-Optimizer#50]
سلام و خسته نباشید.  ما ی سورسی  تازه ای  برای بهینه سازی تر کردن  سرور  پیدا کردیم. خواستم به اشتراک بزارم واسمون 

TCP packet sending algorithm that strives to maintain throughput (effective bandwidth)

https://github.com/marywangran/pixie

**Comment by hawshemi** [comment]
Tested and looked into it.
Good, but it's not simple to implement on an AIO script as it needs to change and compile the kernel.
