### ISSUE TITLE
bpfilter read fail 0

### ISSUE THREAD

**Issue by cdnov** [hawshemi/Linux-Optimizer#54]
**Describe the bug**
bpfilter read fail 0

**Logs**
If applicable, could you add a log to help explain your problem?

**Linux (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**
Please feel free to add any other context about the problem here.

**Comment by hawshemi** [comment]
Can you share more information?

**Comment by hawshemi** [comment]
@cdnov

**Comment by cdnov** [comment]
sorry
<img width="769" alt="img" src="https://github.com/hawshemi/Linux-Optimizer/assets/99079563/063d5263-6e9b-4250-b6ea-fc6cee9d5e4b">

**Comment by hawshemi** [comment]
When this happen?
After reboot and login?

**Comment by cdnov** [comment]
1  - Apply Everything + XanMod Kernel. (RECOMMENDED) 
yes

**Comment by hawshemi** [comment]
What is the OS, the Hardware and the Virtualization?

**Comment by cdnov** [comment]
CPU Model          : Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
 CPU Cores          : 48 @ 1200.045 MHz
 CPU Cache          : 30720 KB
 AES-NI             : ✓ Enabled
 VM-x/AMD-V         : ✓ Enabled
 Total Disk         : 1.3 TB (39.7 GB Used)
 Total Mem          : 62.8 GB (31.6 GB Used)
 System uptime      : 0 days, 7 hour 44 min
 Load average       : 2.02, 1.57, 1.50
 OS                 : Ubuntu 20.04.6 LTS
 Arch               : x86_64 (64 Bit)
 Kernel             : 6.1.66-x64v3-xanmod1
 TCP CC             : bbr
 Virtualization     : Dedicated

**Comment by cdnov** [comment]
Switch back to default Kernel problem solving

**Comment by hawshemi** [comment]
Do you use `iptables` or `nftables` rules on your server?

**Comment by cdnov** [comment]
yes

**Comment by hawshemi** [comment]
what kind and how?
because in some cases, the error you mentioned is about overwriting some `iptables/nftables` rules with the kernel.

**Comment by cdnov** [comment]
The problem occurs as soon as iptables is enabled, and it has nothing to do with the rules

**Comment by cdnov** [comment]
It seems that as long as iptables is enabled, problems will occur regardless of the rules in place.

**Comment by hawshemi** [comment]
Do you mean just `iptables` or `iptables-persistent` ?

**Comment by hawshemi** [comment]
Script Updated.
