### ISSUE TITLE
[SUGGESTION] unInstall XanMod Kernel 

### ISSUE THREAD

**Issue by shakibamoshiri** [hawshemi/Linux-Optimizer#57]
**Is your feature request related to a problem? Please describe.**
for any reason a user might want to remove the installation. For example I tested on Debian 11 and 12. Later for any `apt update -y` it hangs 

**Describe the solution you'd like**
Adding a remove/uninstall option to the bash script 

**Describe alternatives you've considered**
otherwise a user has to do it manually 

**Additional context**
A software without a Ctrl-Z option is incomplete 

Regards

**Comment by hawshemi** [comment]
Thanks.
Yes, you are correct but the main challenge is that after the kernel is changed to Xanmod, the old kernel might be removed with some commands (like `apt autoremove` and such). A rollback feature could be implemented but it can cause some security and/or compatibility risks (As it would be necessary to download a default kernel from somewhere and install it on the server then remove the Xanmod kernel).

But the problem you are experiencing is being connected with DNS or a bad link from your server to Xanmod repositories.

However, I'm implementing a way to roll back to a default Linux kernel.

**Comment by shakibamoshiri** [comment]
actually testing on both Ubuntu and Debian , I did not face issues on Ubuntu but had issue with Debian 11. 
No it was tested outside Iran.
Tested two times on two Debian 11, both had  the same issue
