### ISSUE TITLE
پاکسازی اسکریپت

### ISSUE THREAD

**Issue by Meytiz** [hawshemi/Linux-Optimizer#60]
سلام خسته نباشید برای پاک کردن اسکریپت باید چیکار کرد rm -rf کافیه یا نه؟

**Comment by hawshemi** [comment]
اسکریپت، خودش، جایی نصب نمیشه که بخواد پاک بشه. صرفا یه سری کار هارو روی سرور انجام میده. و قبل انجام اون کارها، از فایل اصلی بکاپ میگیره.

```
Original hosts file is backed up at /etc/hosts.bak.
Original dns file is backed up at /etc/resolv.conf.bak.
Original sysctl.conf file is backed up at /etc/sysctl.conf.bak.
Original ssh file is backed up at /etc/ssh/sshd_config.bak.
```

شما اگر بخاید صرفا میتونید این فایل های بکاپ رو با چیزی که الان هست جایگزین کنید تا تنظیمات اپتیمایز شدهف به حالت قبل برگرده.

**Comment by Meytiz** [comment]
بخوام به حالت اول برگردونم چه کاری باید انجام بدم؟

**Comment by hawshemi** [comment]
@Meytiz 

```
sudo cp /etc/hosts.bak /etc/hosts
```
```
sudo cp /etc/resolv.conf.bak /etc/resolv.conf
```
```
sudo cp /etc/sysctl.conf.bak /etc/sysctl.conf
```
```
sudo cp /etc/ssh/sshd_config.bak /etc/ssh/sshd_config
```
و بعد هم `reboot` کنید تا پیش فرض بشه.

**Comment by Meytiz** [comment]
ی سوال دیگه هم داشتم این سورس چقدر توی کیفیت شبکه سرور تاثیر داره؟

**Comment by hawshemi** [comment]
قرار نیست جادو کنه ولی در بدترین حالت ممکن هیچ فرقی نمیکنه. 
ولی در اکثریت اوقات باعث بهتر شدن Latency و کمتر شدن Packet Loss در اتصالات TCP/UDP میشه. و همچنین محدودیت های سرور رو کمتر میکنه برای Load های بالا.

**Comment by Meytiz** [comment]
بخاطر این پرسیدم که من رو سرور bbrv3 رو ران کردم در کنارش این اسکریپ هم فعال کنم تاثیر میزاره یا نه
