### ISSUE TITLE
افزایش مقذار سوآپ

### ISSUE THREAD

**Issue by hamedefatian** [hawshemi/Linux-Optimizer#64]
سلام و خسته نباشید
من شنیدم مقدار سوآپ باید 2 برابر رم باشه
اگر ممکنه چند حالت سوآپ داشته باشیم بجای اینکه فقط 2 گیگ باشه خیلی خوبه

با تشکر

**Comment by hawshemi** [comment]
مقدار سوآپ بستگی به میزان رم داره. همیشه این نسبت 2 برقرار نیست. 
همینطور وقتی حجم سوآپ بیشتر میشه، نتیجه ی عکس میده در سرعت کلی سیستم. 
برای همین حجم بالای 2گیگ برای سوآپ اصلا پیشنهاد نمیشه.
هدف این اسکریپت هم One-Click بودنشه که فقط یکبار اجرا بشه و کارهارو انجام بده.
اگر بخواید حجم سوآپ رو تغییر بدید، میتونید فایل مورد نظر رو دانلود کنید و داخل کد، صرفا عدد 2 رو به هر عددی که میخواید تغییر بدید و اسکریپت رو اجرا کنید.
