### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [hawshemi/Linux-Optimizer#65]
**Describe the bug**
the customization is quite nice but it thuroughly and agressively disables my nvidia gpu card (3060) can u modify the code so it doesnt touch the gpu?

**Expected behaviour**
optimize network and base system, leave gpu configuration intact

**Logs**
-

**Linux (please complete the following information):**
 - OS:
 ubuntu lts 24.02

**Additional context**
sudo apt install -f nvidia550firmware
sudo apt install -f nvidia550generic.driver
sudo apt install -f nvidia550kernel
install but do not switch to the proper driver

changing the ubuntu "additional driver" gui back and forth from x.org do not succeed

forcing a system update is not possible as im running the latest version

seriously tho wonderfull optimizations, my only recommendations would be to disable auto tuning and pin it to maximum speed for network and use ctcp congestion control provider, cubic is newer but worse.

**Comment by tails1974seeyounextgame** [comment]
sudo su
apt-get remove --purge '^nvidia-.*'
apt-get remove --purge '^libnvidia-.*'
apt-get remove --purge '^cuda-.*'
apt list nv*
#//libnvidia-compute-550 was used and isa headless gpu from zan1 package conflicts with all other nvidia components
*nvidia-compute* hold|dpkg --set-selections
apt upgrade nvidia*
apt install -f nvidia-kernel-common-550
apt install -f nvidia-firmware-550-550.67
apt install -f nvidia-utils-550
sleep 500
reboot

**Comment by hawshemi** [comment]
You'll see no GPU optimization commands if you look at the code and optimizations. The script would not touch anything GPU-related.
The congestion control is BBRv3 (if XanMod is installed), as BBRv3 is the latest Google update for BBrv2 and the most stable and low-latency congestion control.

**Comment by tails1974seeyounextgame** [comment]
it removes the drivers by changing the kernel itself

    On Saturday, June 15, 2024 at 01:51:53 AM MST, Hawshemi ***@***.***> wrote:  
 
 


You'll see no GPU optimization commands if you look at the code and optimizations. The script would not touch anything GPU-related.
The congestion control is BBRv3 (if XanMod is installed), as BBRv3 is the latest Google update for BBrv2 and the most stable and low-latency congestion control.

**Comment by tails1974seeyounextgame** [comment]
so to better optimize your script i would simply suggest converting all the other options into the default option 1, then for option 2 install zan kernel also this works fine
sudo su| apt update -q && apt install -y wget|sudo -i|wget "https://raw.githubusercontent.com/hawshemi/Linux-Optimizer/main/linux-optimizer.sh" -O linux-optimizer.sh && chmod +x linux-optimizer.sh && bash linux-optimizer.sh

**Comment by tails1974seeyounextgame** [comment]
feel free to purge these comments once the changes have been made o/

**Comment by hawshemi** [comment]
Yes. Thanks for the comment. I'll make sure to add it.
But as you may know, this script is intended to run on Linux Servers like VPS, VDS, Dedicated Servers, and ...
